### ISSUE TITLE
Estacionamento: mapa de clientes e prioridade para vaga

### ISSUE THREAD

**Issue by joaocaram** [DisciplinasProgramacao/projeto3-g6#54]

**Comment by joaocaram** [comment]
@Salomao0tavio pelo que entendi, você acabou pegando estes requisitos da Larissa para fazer. A Larissa ainda está no grupo. Por favor, então, termine as ações:

- a fila de prioridades deve ser um atributo do Estacionamento, e não somente criada na hora de procurar vagas (senão vai criar e apagar toda hora)
- é necessário fazer parecido com os clientes e transformar o vetor em um mapa de Clientes

Quando assumir um requisito, por favor passe para seu nome aqui, senão eu não tenho como avaliar direito depois.

**Comment by Salomao0tavio** [comment]
@joaocaram nao sei porque ela esta pra mim, eu nao atribui, mas nas próximas te aviso sim

**Comment by joaocaram** [comment]
@Salomao0tavio Eu mudei ela para você porque você fez o código apesar de ela estar para outra pessoa antes.
